#!/bin/bash
set -eou pipefail

ctl_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_dir="$(cd "$(dirname "$ctl_dir")" && pwd)"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

function error {
	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}: line ${BASH_LINENO[0]}: ${*}"
	>&2 echo -e "${RED}${msg}${NC}"
	exit 2
}

args=()
debug=()

# shellcheck disable=SC2214
while getopts ':defip-:' OPT; do
	if [ "$OPT" = "-" ]; then     # long option: reformulate OPT and OPTARG
		OPT="${OPTARG%%=*}"       # extract long option name
		OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
		OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
	fi
	case "$OPT" in
		d|dev ) dev="true";;
		e|enter ) enter="true";;
		f|fast ) fast="true"; args+=( "--fast" );;
		i|inside ) inside="true"; args+=( "--inside" );;
		p|prepare ) prepare="true"; args+=( "--prepare" );;
		ctl ) ctl="true";;
		debug ) debug=( "-vvvvv" ); args+=( "--debug" );;
		no-vault ) no_vault="true";;
		\? ) error "[error] unknown short option: -${OPTARG:-}";;
		?* ) error "[error] unknown long option: --${OPT:-}";;
	esac
done
shift $((OPTIND-1))

project="${1:-}"
ctl_title="[ctl]"

if [ "${dev:-}" = "true" ]; then
	ctl_title="[ctl - dev mode]"
fi

start="$(date '+%F %T')"
echo -e "${CYAN}$start $ctl_title [start] running the project ($project)${NC}"

if [ -z "$project" ]; then
	error "[error] $ctl_title enter the project name"
fi

shift;

if [ -n "${1:-}" ]; then
	args+=( "--" );
fi

if [ "${dev:-}" = 'true' ]; then
    ln -rsfT "${root_dir}" "${root_dir}/link"
fi

secrets_dir_rel="secrets/projects/$project"
secrets_dir="$root_dir/$secrets_dir_rel"

[ "${inside:-}" = 'true' ] && root_dir_inside="$root_dir" || root_dir_inside="/main"
[ "${inside:-}" = 'true' ] && secrets_dir_cmd="$secrets_dir" || secrets_dir_cmd="/main/$secrets_dir_rel"
[ "${inside:-}" = 'true' ] && hosts_file="$ctl_dir/ansible/hosts" || hosts_file="/main/ctl/ansible/hosts"

vault=()

if [ "${no_vault:-}" != "true" ]; then
	mkdir -p "$secrets_dir"

	vault_file="$secrets_dir/vault"

	if [ ! -f "$vault_file" ]; then
		echo -n "Enter the main vault pass (to decrypt the ssh keys of the environment repositories): "
		read -r -s vault_pass
		echo

		touch "$vault_file"
		chmod 600 "$vault_file"
		echo "$vault_pass" > "$vault_file"
	fi

	vault=( '--vault-id' "$secrets_dir_cmd/vault" )
fi

# shellcheck source=./files/env.sample.sh
source "${ctl_dir}/env-main/env.sh"

var_container="$container"
var_container_type="${container_type:-}"
var_allow_container_type="${allow_container_type:-}"
var_root="${root:-}"
var_main_user_group="${main_user_group:-}"
var_subuser_group="${subuser_group:-}"
var_subuser_prefix="${subuser_prefix:-}"

main_user="$(whoami)"
subuser="${var_subuser_prefix}${project}"

if [ "$var_container_type" = "" ]; then
	var_container_type="docker"
fi

if [ "$var_allow_container_type" != 'true' ]; then
	if [ "$var_container_type" != 'docker' ] && [ "$var_container_type" != 'podman' ]; then
		error "[error] $ctl_title unsupported container type: $var_container_type"
	fi
fi

container_cmd=( "$var_container_type" )

if [ "$var_root" = 'true' ]; then
    container_cmd=( sudo "$var_container_type" )
fi

if [ "${fast:-}" = 'true' ]; then
	echo "$ctl_title skipping init project (fast)..."
else
    prepare_args=()
	skip=''

    if [ "${prepare:-}" = 'true' ]; then
		if [ "${1:-}" = "--skip" ]; then
			skip='true';
			shift;
		else
			for arg in "$@"; do
				shift;

				if [ "$arg" = "--" ]; then
					break;
				fi

				prepare_args+=( "$arg" )
			done
		fi
    fi

	if [ "${skip:-}" = 'true' ]; then
		echo "$ctl_title skipping init project (skip)..."
	else
		if [ -n "$var_main_user_group" ] || [ -n "$var_subuser_group" ]; then
			if [ -z "$var_main_user_group" ]; then
				error "[error] subuser_group($var_subuser_group) was specified, but main_user_group was not specified"
			elif [ -z "$var_subuser_group" ]; then
				error "[error] main_user_group($var_main_user_group) was specified, but subuser_group was not specified"
			fi

			echo "[ctl] creating and defining user $subuser - start..."

			sudo groupadd -f "$var_main_user_group" || error "[error] create main user group"
			sudo usermod -a -G "$var_main_user_group" "$main_user" || error "[error] add main user to group"

			subuser_home_base_dir="${root_dir}/projects/$project/user"
			subuser_home_dir="$subuser_home_base_dir/$subuser"
			sudo mkdir -p "$subuser_home_base_dir"

			if ! id -u "$subuser" &>/dev/null; then
				sudo rm -rf "$subuser_home_dir"
				sudo useradd "$subuser" --create-home  --home-dir "$subuser_home_dir" --shell /bin/bash \
					|| error "[error] create subuser"
				sudo chown "$subuser":"$subuser" "$subuser_home_base_dir"
				sudo chown "$subuser":"$subuser" "$subuser_home_dir"
				sudo passwd -l "$subuser" || error "[error] disable subuser login"
			fi

			sudo groupadd -f "$var_subuser_group" || error "[error] create subuser group"
			sudo usermod -a -G "$var_subuser_group" "$subuser" || error "[error] add subuser to group"

			sudo mkdir -p "${root_dir}/projects/$project"
			sudo chown "$subuser":"$subuser" "${root_dir}/projects/$project"
			sudo mkdir -p "${root_dir}/secrets/projects/$project"
			sudo chown "$subuser":"$subuser" "${root_dir}/secrets/projects/$project"

			echo "[ctl] creating and defining user $subuser - end"
		fi

		inner_cmd=( \
			ansible-playbook \
			${vault[@]+"${vault[@]}"} \
			${debug[@]+"${debug[@]}"} \
			-i "$hosts_file" \
			--extra-vars "env_root_dir=$root_dir_inside" \
			--extra-vars "env_project_key=$project" \
			--extra-vars "env_dev=${dev:-}" \
			ansible/main.yml \
			${prepare_args[@]+"${prepare_args[@]}"} \
		)

		if [ "${enter:-}" = 'true' ]; then
			mkdir -p "$ctl_dir/tmp"
			echo "${inner_cmd[@]+"${inner_cmd[*]}"}" > "$ctl_dir/tmp/cmd"
			inner_cmd=( /bin/bash )
		fi

		error_msg="[error] [ctl] project run - prepare"

		if [ "${inside:-}" = 'true' ]; then
			error_msg="$error_msg (inside)"
			export ANSIBLE_CONFIG="$ctl_dir/ansible/ansible.cfg"

			if [ -z "$var_subuser_group" ]; then
				cd "$ctl_dir"
				"${inner_cmd[@]}" || error "$error_msg (same user)"
			else
				sudo su - "$subuser" bash || error "$error_msg (as $subuser)" <<-SHELL
					set -eou pipefail
					cd "$ctl_dir"
					${inner_cmd[@]}
				SHELL
			fi
		else
			cmd=( \
				"${container_cmd[@]}" run --rm -it \
					--name="local-ctl-$project" \
					--workdir "/main/ctl" \
					-v "${ctl_dir}:/main/ctl:ro" \
					-v "${root_dir}/projects/$project:/main/projects/$project" \
					-v "${root_dir}/secrets/projects/$project:/main/secrets/projects/$project" \
					-e ANSIBLE_CONFIG=/main/ctl/ansible/ansible.cfg \
					"$var_container" \
					${inner_cmd[@]+"${inner_cmd[@]}"} \
			)

			if [ -z "$var_subuser_group" ]; then
				"${cmd[@]}" || error "$error_msg (same user)"
			else
				sudo su - "$subuser" <<-SHELL || error "$error_msg (as $subuser)"
					set -eou pipefail
					${cmd[@]}
				SHELL
			fi
		fi
	fi
fi

if [ "${enter:-}" != 'true' ] && [ "${ctl:-}" != 'true' ]; then
	cmd=( bash "${root_dir}/projects/$project/files/ctl/run" ${args[@]+"${args[@]}"} "${@}" )
	error_msg="[error] $ctl_title project $project - run"

	if [ -z "$var_subuser_group" ]; then
		"${cmd[@]}" || error "$error_msg (same user)"
	else
		sudo su - "$subuser" <<-SHELL || error "$error_msg (as $subuser)"
			set -eou pipefail
			${cmd[@]}
		SHELL
	fi
fi

end="$(date '+%F %T')"
echo -e "${CYAN}$end $ctl_title [end] running the project ($project)${NC}"

echo -e "${GREEN}$ctl_title [project - $project] [run] summary - $start to $end ${NC}"
