- name: Play 01 - Prepare [{{ env_local_repo }}]
  hosts: main
  gather_facts: no  
  tasks:  

  - name: "[ctl - env] [prepare]"
    include_tasks: "tasks/main_vars.yml"
    tags: ["other"]

  - name: "{{ main_title }} [prepare] [{{ env_local_repo }}]"
    set_fact: 
      repo: >-
        {{ 
        env.repos | selectattr('local_repo', 'equalto', env_local_repo) | first | default({}) 
        }}
    tags: ["other", "no_print"]

  - name: "{{ main_title }} [prepare] - [{{ env_local_repo }}] fail - repo not found"
    fail:
      msg: "the repository was not found [{{ repo.name }}]"
    when: (repo.local_repo | default('')) == ''
    tags: ["other"]

  - name: "{{ main_title }} [prepare] [{{ env_local_repo }}]"
    set_fact: 
      repo_title: "{{ main_title }} [prepare] [{{ env_local_repo }}]"
    tags: ["other", "no_print"]

  - name: "{{ repo_title }}"
    include_tasks: "tasks/repo_vars.yml"
    tags: ["other"]

  # repo env vars

  - name: "{{ repo_title }} - env"
    include_tasks: "tasks/env.yml"
    vars:
      repo_env_title: "{{ repo_title }} - env"
      repo_env_file: "{{ repo_env_dest }}/{{ repo.env_file }}"
      repo_env_ctx: ""
      repo_env_ctxs: "{{ repo.ctxs | default([]) }}"
      repo_env_dir: "{{ repo_env_dest }}"
      repo_env_ctl: true
      repo_env_main_dev: "{{ main_dev }}"
      repo_env_repo: "{{ repo }}"
      repo_env_repo_dest: "{{ repo_dest }}"
    tags: ["other"]

  # repo ctxs

  - name: "{{ repo_title }}"
    set_fact: 
      repo_env_aux: "{{ repo_env | combine({}) }}"
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - copy the executable repo ctx files"
    include_tasks: "tasks/scripts.ctx.yml"
    vars:
      repo_env_inner: "{{ repo_env_aux | combine({ 'ctx': repo_item }) }}"
    loop: "{{ repo_env.ctxs }}"
    loop_control:
      loop_var: repo_item
    tags: ["other"]
      
  - name: "{{ repo_title }} - copy the main executable files"
    template:
      src: "templates/run.tpl.sh"
      dest: "{{ repo_dest }}/{{ repo_item }}"
      mode: 0700
    vars:
      repo_dir: "{{ repo_dest }}"
      repo_file: "{{ repo_item }}"
      repo_env_ctxs: "{{ repo_env.ctxs }}"
    loop:
    - "run"
    - "upgrade"
    - "run-fast"
    loop_control:
      loop_var: repo_item
    tags: ["other"]

  # repo ssh

  - name: "{{ repo_title }} - define node names"
    set_fact: 
      repo_env_nodes_list: []
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - define nodes"
    set_fact: 
      repo_env_nodes_list: "{{ repo_env_nodes_list + tmp_nodes }}"
    vars:
      tmp_nodes: "{{ repo_env.main[repo_item].nodes | default([]) }}"
    loop: "{{ repo_env.ctxs | default([]) }}"
    loop_control:
      loop_var: repo_item
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - define node names (create)"
    set_fact: 
      repo_env_nodes_all: []
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - define node names"
    set_fact: 
      repo_env_nodes_all: "{{ repo_env_nodes_all + [tmp_node] }}"
    vars:
      tmp_node: "{{ repo_item.name | default(repo_item) }}"
    loop: "{{ repo_env_nodes_list | default([]) }}"
    loop_control:
      loop_var: repo_item
      label: "{{ tmp_node }}"
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - define unique node names"
    set_fact: 
      repo_env_nodes: "{{ repo_env_nodes_all | unique }}"
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - verify unique node names"
    fail: 
      repo_env_nodes: "There are duplicated node names in your settings"
    when: (repo_env_nodes | length) != (repo_env_nodes_all | length)
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - copy the ssh executable files"
    template:
      src: "templates/ssh.tpl.sh"
      dest: "{{ repo_dest }}/ssh"
      mode: 0700
    vars:
      repo_dir: "{{ repo_dest }}"
      repo_env_ctxs: "{{ repo_env.ctxs }}"
      repo_ssh_default_ctx: "{{ repo.default_ctx | default('') }}"
      repo_ssh_default_node: "{{ repo.default_node | default('') }}"
    tags: ["other"]