- name: "{{ repo_title }}"
  set_fact:
    repo_inner_title: "{{ repo_title }} - {{ repo_env_inner.ctx }}"
    repo_inner_var_dir: "{{ repo_dest }}/ctx/{{ repo_env_inner.ctx }}/var"
    repo_inner_cloud_dir: "{{ repo_dest }}/ctx/{{ repo_env_inner.ctx }}/cloud"
  tags: ["other", "no_print"]

- name: "{{ repo_inner_title }}"
  include_tasks: "tasks/repo_main_params.yml"
  tags: ["other"]

# repo cloud repository

- name: "{{ repo_inner_title }}"
  set_fact:
    repo_cloud_dest: >-
      {{ 
      (main_dev | bool) | 
      ternary(
      repo.local_cloud_dir | default('') | 
      ternary(main_cloud_repo_dest_base + '/' + (repo.local_cloud_dir | default('')), ''), 
      repo_inner_cloud_dir
      )
      }}
  tags: ["other", "no_print"]

- name: "{{ repo_inner_title }} - fail - repo_cloud_dest"
  fail:
    msg: "local_cloud_dir is not defined for the repository [{{ repo.name }}]"
  when: (repo_cloud_dest | default('')) == ''
  tags: ["other"]

- name: "{{ repo_inner_title }}"
  set_fact: 
    repo_cloud: "{{ repo_env_inner.repos[repo_env_main_params.repo] }}"
  tags: ["other", "no_print"]

- name: "{{ repo_inner_title }}"
  include_tasks: "tasks/git.yml"
  vars:
    git_title: "{{ repo_inner_title }} - git cloud repo ({{ repo_env_main_params.repo }})"
    git_repo_private: "{{ repo_cloud.private | default(false) }}"
    git_repo_key_file_encrypted: >-
      {{ repo_env_dest }}/{{ repo_cloud.key_file_encrypted | default('') }}
    git_repo_src: "{{ repo_cloud.src }}"
    git_repo_version: "{{ repo_cloud.version }}"
    git_repo_key_file: "{{ repo_inner_var_dir }}/repo/cloud.key_file"
    git_repo_accept_hostkey: yes
    git_repo_dest: "{{ repo_cloud_dest }}"
    git_repo_update: "{{ (main_dev | bool) | ternary('no', 'yes') }}"
    git_repo_force: no
    git_task_tags: ["other"]
  tags: ["other"]

- name: "{{ repo_inner_title }}"
  include_tasks: "tasks/git.yml"
  vars:
    repo_env_repo: "{{ repo_env_inner.repos[repo_env_repo_data.repo] }}"
    git_title: "{{ repo_inner_title }} - git cloud env repo ({{ repo_env_repo_data.repo }})"
    git_repo_private: "{{ repo_env_repo.private | default(false) }}"
    git_repo_key_file_encrypted: >-
      {{ repo_env_dest }}/{{ repo_env_repo.key_file_encrypted | default('') }}
    git_repo_src: "{{ repo_env_repo.src }}"
    git_repo_version: "{{ repo_env_repo.version }}"
    git_repo_key_file: "{{ repo_inner_var_dir }}/repo/{{ repo_env_repo_data.dir }}/cloud.key_file"
    git_repo_accept_hostkey: yes
    git_repo_dest: "{{ repo_cloud_dest }}/{{ repo_env_repo_data.dir }}"
    git_repo_update: "{{ (main_dev | bool) | ternary('no', 'yes') }}"
    git_repo_force: no
    git_task_tags: ["other"]
  loop: "{{ repo_env_main_params.env_repos | default([]) }}"
  loop_control:
    loop_var: repo_env_repo_data
    label: "{{ repo_env_repo_data.repo }}"

# repo cloud entrypoint
    
- name: "{{ repo_inner_title }}"
  fail:
    msg: >-
      {{ repo_inner_title }} - the environment file init parameter doesn't contain
      the entrypoint property defined
  when: (repo_env_main_params.entrypoint | default('')) == ''
  tags: ["other"]

- name: "{{ repo_inner_title }}"
  include_tasks: "tasks/template.yml"
  vars:
    template_title: "{{ repo_inner_title }} - entrypoint ({{ repo_env_main_params.entrypoint_template_src }})"
    template_src: "{{ repo_cloud_dest }}/{{ repo_env_main_params.entrypoint_template_src }}"
    template_tmp_dest: "{{ repo_inner_var_dir }}/cloud-entrypoint/{{ repo_env_main_params.entrypoint }}"
    template_dest: "{{ repo_cloud_dest }}/{{ repo_env_main_params.entrypoint }}"
    template_remote_src: false
    template_local: true
    template_params: "{{ repo_env_inner }}"
    template_ctl_params: "{{ repo }}"
    template_local_params:
      base_dir_pod: "{{ repo_base_dir_pod }}"
      base_dir_app: "{{ repo_base_dir_app }}"
    template_meta: "{{ repo_env_inner.meta_params[repo_env_main_params.meta | default('')] | default({}) }}"
    template_task_tags: ["other"]
  when: (repo_env_main_params.entrypoint_template_src | default('')) != ''
  tags: ["other"]

# repo hosts file (inventory)

- name: "{{ repo_inner_title }}"
  set_fact: 
    repo_hosts_file_src: >-
      {{ 
      repo_env_main_params.hosts_file | default('')
      | ternary(repo_env_dest + '/' + (repo_env_main_params.hosts_file | default('')), '')
      }}
    repo_hosts_content: "{{ repo_env_main_params.hosts_content | default('') }}"
  tags: ["other", "no_print"]

- name: "{{ repo_inner_title }} - ensure that there is a hosts file or content"
  fail:
    msg: "Enter a value for hosts_file or hosts_content"
  when: >-
    ((repo_hosts_file_src | default('')) == '') 
    and 
    ((repo_hosts_content | default('')) == '')
  tags: ["other"]

- name: "{{ repo_inner_title }} - ensure that there isn't a hosts file and a hosts content at once"
  fail:
    msg: "Enter a value for only one of hosts_file or hosts_content"
  when: >-
    ((repo_hosts_file_src | default('')) != '') 
    and 
    ((repo_hosts_content | default('')) != '')
  tags: ["other"]

- name: "{{ repo_inner_title }} - copy the hosts file temporarily to verify changes"
  copy:
    src: "{{ repo_hosts_file_src }}"
    dest: "{{ repo_inner_var_dir }}/hosts.tmp"
    mode: 0600
  register: diff_hosts_file
  when: (repo_hosts_file_src | default('')) != ''
  tags: ["other"]

- name: "{{ repo_inner_title }} - copy the hosts content temporarily to verify changes"
  copy:
    content: "{{ repo_hosts_content }}"
    dest: "{{ repo_inner_var_dir }}/hosts.tmp"
    mode: 0600
  register: diff_hosts_content
  when: (repo_hosts_content | default('')) != ''
  tags: ["other"]

- name: "{{ repo_inner_title }} - copy the hosts file when changed"
  copy:
    src: "{{ repo_inner_var_dir }}/hosts.tmp"
    dest: "{{ repo_inner_var_dir }}/hosts"
    mode: 0600
    force: "{{ diff_hosts_file.changed or diff_hosts_content.changed }}"
  tags: ["other"]
