#!/bin/bash
set -eou pipefail

run_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ctl_dir="$(dirname "$(dirname "$run_dir")")"
base_dir="$(dirname "$ctl_dir")"

local_repo_name="$1"
local_pod_name="${2:-}"

if [ ! -z "$local_pod_name" ]; then
    "$base_dir/pod/$local_pod_name/run" migrate
    "$base_dir/pod/$local_pod_name/run" backup
fi

"$ctl_dir/run" main-dev-deploy "$local_repo_name"

if [ ! -z "$local_pod_name" ]; then
    "$base_dir/pod/$local_pod_name/run" stop
fi
