namespace: "lrd"
name: "ctl"
version: "1.0.12"
readme: "README.md"
authors:
    - "Lucas Basquerotto"
dependencies: {}
license:
    - "MIT"
tags:
    - demo
    - collection
repository: "https://www.github.com/my_org/my_collection"