#!/bin/bash
set -eou pipefail

run_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ctl_dir="$(dirname "$(dirname "$run_dir")")"
base_dir="$(dirname "$ctl_dir")"

local_repo_name="$1"
env_node="$2"
env_exec_become="$3"
# E.g.: exec_app
set -- "${@:4}"

args="$@"
args_encoded=''

if [ ! -z "$args" ]; then
    args_encoded=$(echo "$args" | base64 -w 0)
fi

"$ctl_dir/run" fast-deploy "$local_repo_name" \
  --tags "exec" \
  -e env_node="$env_node" \
  -e env_exec_become="$env_exec_become" \
  -e env_exec_cmd="$args_encoded"
