{% set var_local = params.local | bool %}

{% set var_use_internal_fluentd = params.use_internal_fluentd | bool %}
{% set var_fluentd_ssl =
  (params.fluentd_output_plugin == 'elasticsearch')
  and
  (params.use_secure_elasticsearch | bool)
%}

version: '3.7'

x-logging:

  {#############################################################}
  {% if params.use_fluentd | bool %}

  mainlog: &mainlog
    driver: "fluentd"
    options:
      tag: "{% raw %}docker.{{.Name}}{% endraw %}"
      fluentd-address: "localhost:{{ params.fluentd_port }}"
  jsonlog: &jsonlog
    driver: "json-file"
    options:
      max-size: "50m"

  {% else %}

  mainlog: &mainlog
    driver: "json-file"
    options:
      max-size: "50m"

  {% endif %}
  {#############################################################}

services:

  toolbox:
    container_name: "ctl-toolbox"
    hostname: "toolbox"
    image: "{{ params.images.toolbox_image }}:{{ params.images.toolbox_version }}"
    restart: "unless-stopped"

    {#############################################################}
    {% if var_use_internal_fluentd %}

    depends_on:
    - "fluentd"

    {% endif %}
    {#############################################################}

    {#############################################################}
    {% if var_local %}

    extra_hosts:
      host.docker.internal: host-gateway

    {% endif %}
    {#############################################################}

    volumes:
    - "{{ params.data_dir }}:/var/main/data"
    - "{{ params.data_dir }}/tmp:/tmp/main"
    - "{{ params.data_dir }}/log:/var/log/main"

    {#############################################################}
    {% if params.use_internal_ssl | bool %}

    - "./env/ssl:/etc/ssl:ro"

    {% endif %}
    {#############################################################}

    logging: *mainlog
    command: "tail -f /dev/null"

    {#############################################################}
    {% if (params.memory.toolbox | default('')) != '' %}

    mem_limit: "{{ params.memory.toolbox }}"

    {% endif %}
    {#############################################################}

  {#############################################################}
  {% if var_use_internal_fluentd %}

  fluentd:
    container_name: "ctl-fluentd"
    hostname: "fluentd"
    image: "{{ params.images.fluentd_image }}:{{ params.images.fluentd_version }}"
    restart: "unless-stopped"
    ports:
    - "{{ params.fluentd_port }}:24224"
    - "{{ params.fluentd_port }}:24224/udp"

    {#############################################################}
    {% if var_local %}

    extra_hosts:
      host.docker.internal: host-gateway

    {% endif %}
    {#############################################################}

    volumes:

    {#############################################################}
    {% if var_fluentd_ssl %}

    - "./env/ssl:/etc/ssl:ro"

    {% endif %}
    {#############################################################}

    - "{{ params.data_dir }}/log/fluentd:/var/log/main/fluentd"
    - "{{ params.data_dir }}/tmp/fluentd:/tmp/main/fluentd"
    - "{{ params.data_dir }}/tmp/tmp/fluentd:/tmp/main/tmp/fluentd"
    logging: *jsonlog

    {#############################################################}
    {% if (params.memory.fluentd | default('')) != '' %}

    mem_limit: "{{ params.memory.fluentd }}"

    {% endif %}
    {#############################################################}

  {% endif %}
  {#############################################################}
