#!/bin/bash
set -eou pipefail

run_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ctl_dir="$(dirname "$run_dir")"
base_dir="$(dirname "$ctl_dir")"

repo_name="$1"
instance_type="$2"
index="${3:-1}"

RED='\033[0;31m'
NC='\033[0m' # No Color

repo_dir="$base_dir/r/w/$repo_name"
hosts_file="$repo_dir/var/hosts"

line=$(cat "$hosts_file" | grep "instance_type=$instance_type" | head -n "$index" | tail -n 1 || :)

if [ -z "$line" ]; then
    msg="No line in the hosts file ($hosts_file)"
    msg="$msg of the type '$instance_type' in the index $index (starting in 1)."
    echo -e "${RED}${msg}${NC}"
    exit 1
fi

user=$(echo "$line" | sed -n -e 's/^.*ansible_user=//p' | awk '{ print $1 }')
host=$(echo "$line" | sed -n -e 's/^.*ansible_host=//p' | awk '{ print $1 }')
key_file=$(echo "$line" | sed -n -e 's/^.*ansible_ssh_private_key_file=//p' | awk '{ print $1 }')

if [ -z "$key_file" ]; then
    echo "ssh $user@$host"
    ssh "$user@$host"
else
    key_file=$(echo "$key_file" | sed "s!^/root!$base_dir!")
    echo "ssh -i $key_file $user@$host"
    ssh -i "$key_file" "$user@$host"
fi
