- name: Play 01 - Prepare the project
  hosts: main
  tasks:
    ### Main - Start ###

    - name: "[project - {{ env_project_key | default('') }}] [ctl] - initial vars"
      set_fact:
        project_title: "[project - {{ env_project_key | default('') }}] [ctl]"
        env_main_dir: "{{ env_root_dir }}/ctl/env-main"
      tags: ["no_print"]

    - name: "{{ project_title }} - load the main environment vars"
      include_vars:
        file: "{{ env_main_dir }}/vars.yml"
        name: env

    - name: "{{ project_title }} - vars - prepare"
      set_fact:
        project_vars: "{{ env | lrd.ctl.prepare(args=tmp_args) }}"
      vars:
        tmp_args:
          env_root_dir: "{{ env_root_dir }}"
          env_project_dir_relpath: "{{ env_project_dir_relpath }}"
          env_project_key: "{{ env_project_key }}"
          env_dev: "{{ env_dev }}"
          env_migration: "{{ env_migration }}"
      tags: ["no_print"]

    ### Project - Directories and Files ###

    - name: "{{ project_title }} - define the project directories"
      set_fact:
        project_base_dir: "{{ tmp_main_root_dir }}/{{ env_project_dir_relpath }}"
        project_secrets_base_dir: "{{ tmp_secrets_base_dir }}"
        project_files_base_dir: "{{ tmp_files_base_dir }}"
        project_secrets_dir: "{{ tmp_secrets_base_dir }}/ctl"
        project_files_dir: "{{ tmp_files_base_dir }}/ctl"
      vars:
        tmp_main_root_dir: "{{ env_root_dir }}"
        tmp_secrets_base_dir: "{{ tmp_main_root_dir }}/{{ env_project_dir_relpath }}/secrets"
        tmp_files_base_dir: "{{ tmp_main_root_dir }}/{{ env_project_dir_relpath }}/files"
      no_log: "{{ project_vars.no_log | default(omit, true) }}"
      tags: ["no_print"]

    - name: "{{ project_title }} - create the project directories"
      file:
        path: "{{ project_item }}"
        state: directory
        mode: "{{ project_vars.lax | default(false, true) | bool | ternary('777', '755') }}"
      loop:
        - "{{ project_base_dir }}"
        - "{{ project_secrets_base_dir }}"
        - "{{ project_files_base_dir }}"
        - "{{ project_secrets_dir }}"
        - "{{ project_files_dir }}"
      loop_control:
        loop_var: project_item
      no_log: "{{ project_vars.no_log | default(omit, true) }}"

    - name: "{{ project_title }} - create the project files"
      copy:
        content: "{{ project_item.content | default(omit, true) }}"
        src: "{{ project_item.src | default(omit, true) }}"
        dest: "{{ project_item.dest }}"
        mode: "{{ project_item.mode }}"
      loop:
        - src: "{{ env_main_dir }}/{{ project_vars.repo.ssh_file | default('') }}"
          dest: "{{ project_secrets_dir }}/{{ project_vars.repo_ssh_file }}"
          mode: "0600"
          when: "{{ project_vars.repo_ssh_file != '' }}"
        - src: "{{ env_main_dir }}/{{ project_vars.repo_vault.file | default('') }}"
          dest: "{{ project_secrets_dir }}/{{ project_vars.repo_vault_file }}"
          mode: "{{ project_vars.lax | default(false, true) | bool | ternary('666', '600') }}"
          when: "{{ project_vars.repo_vault_file != '' }}"
        - content: "{{ project_vars.init_vars | to_nice_yaml }}"
          dest: "{{ project_files_dir }}/vars.yml"
          mode: "{{ project_vars.lax | default(false, true) | bool | ternary('666', '600') }}"
        - content: "{{ project_vars.init_shell_vars_content }}"
          dest: "{{ project_files_dir }}/vars.sh"
          mode: "{{ project_vars.lax | default(false, true) | bool | ternary('666', '600') }}"
        - src: "run"
          dest: "{{ project_files_dir }}/run"
          mode: "{{ project_vars.lax | default(false, true) | bool | ternary('777', '711') }}"
      when: project_item.when | default(true) | bool
      loop_control:
        loop_var: project_item
        label: "{{ project_item.dest }}"
      no_log: "{{ project_vars.no_log | default(omit, true) }}"
