#!/bin/bash
export key=''
export dev=''
export project_dir_relpath=''
export container=''
export container_type=''
export allow_container_type=''
export root=''
export run_file=''
export force_vault=''